workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
